apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hackathon-kube-app
  template:
    metadata:
      labels:
        app: hackathon-kube-app
    spec:
      containers:
      - name: g-aks-c7-team9
        image: hackathonteam9/python-app:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-kube-svc
spec:
  selector:
    app: hackathon-kube-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
